### ISSUE TITLE
Floating point parsing assumes US decimal convention.

### ISSUE THREAD

**Issue by hersh** [moveit/moveit_commander#11]
Many places in interpreter.py use code like `float(str)` to parse a string into a floating point value.  Unfortunately Python does not default to using locale-specific float parsing, so in places where "," (comma) is used for the decimal, this fails.

The correct thing is to use `locale.atof(str)` instead, along with

```
import locale
locale.setlocale(locale.LC_ALL, '')
```

at the beginning.

Source: http://docs.python.org/2/library/locale.html#locale.atof

**Comment by mintar** [comment]
I don't think config files, command line commands, UI commands or anything similar should be localized.

Coming from Germany, a country which uses the comma as the default decimal separator, I know that this sucks. It's basically always a bug. Imagine if there were URDF files from the States that don't work in Europe, or C++ files that only compile on German locales.

Oh, the US locale is also called the POSIX or C locale in order to sound less imperialistic. ;-)

**Comment by hersh** [comment]
Good point @mintar .  As it turns out, this was reported on moveit_setup_assistant back in Groovy ( https://github.com/ros-planning/moveit_setup_assistant/issues/51 ), and then closed without fixing it.  I re-opened that, hopefully we can get it fixed this time.

Closing this bug, as I agree that file formats and commands are better if uniform.
